name: crop_your_image
description: crop_your_image helps your app to embed Widgets for cropping images.
version: 2.1.0
homepage: https://github.com/chooyan-eng/crop_your_image
topics:
  - crop
  - image-cropper
  - image

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  image: ^4.8.0
  heic_to_png_jpg: ^0.1.1
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
