name: run-flutter-test
on: [push, pull_request]
jobs:
  first:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter test